# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'WWDC15' do

pod 'PureLayout'
pod 'NSUserDefaults+Subscripting'
pod 'PMTween'
pod 'MZFormSheetController'

end

target 'WWDC15Tests' do

end

